import Head from 'next/head';
import Header from '../components/header';
import Footer from '../components/footer';
import StoreWrapper from '../store';

import '../styles/globals.scss';

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StoreWrapper session={session}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </StoreWrapper>
    </>
  );
}
